version: '3.4'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: prod

  tests:
    profiles:
      - test
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: test
    command: test
    volumes:
      - ..:/app
