[tool.poetry]
name = "generator"
version = "0.1.0"
description = ""
authors = ["Platon Floria <platon.floria@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sympy = "^1.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
